### ISSUE TITLE
从主页跳转 MyBatis 和 Spring MVC Page 404

### ISSUE THREAD

**Issue by chaoqi2080** [guobinhit/cg-blog#4]
https://github.com/guobinhit/cg-blog/blob/master/articles/mybatis/MYBATIS_README.md
https://github.com/guobinhit/cg-blog/blob/master/articles/mybatis/README.md
直接跳转链接是第一个，有效链接是第二个

**Comment by guobinhit** [comment]
非常感谢，已修复！
