### ISSUE TITLE
这边SpringMVC 教程里面的连接文章怎么打不开呢？

### ISSUE THREAD

**Issue by JKAK47** [guobinhit/cg-blog#6]
https://github.com/guobinhit/springmvc-tutorial/blob/master/articles-of-springmvc/buildspringmvc.md

**Comment by guobinhit** [comment]
你好，该问题已修复！之前的连接失效了。不过这个系列的文章已经有些久了，也有其他方式来搭建 Spring MVC 框架，如不通过 XML 进行配置，仅使用 JavaConfig 等。大致看看就可以啦~祝你顺利！
