### ISSUE TITLE
关于star术语的解释的建议

### ISSUE THREAD

**Issue by HaneChiri** [guobinhit/cg-blog#7]
在本库的《github术语解释》中，把star当成点赞，但是我认为当成收藏更为合适。
第一，收藏比点赞更加难得，github上面的star是比较难得的，不像点赞那么容易。
第二，star的内容可以查看，就和放进收藏夹差不多，点赞则一般不能查看（当然也有一些可以）
第三，点赞和收藏都可以表达对项目的认可，而且收藏表达的认可程度更加高一些。
第四，收藏的图标一般是个星星（star）嘛
以上只是我作为一个萌新的理解，可能不太准确。

**Comment by guobinhit** [comment]
嗯，确实不错，理解为收藏其实也挺好的。
